<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="xunit" Version="2.9.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Spectre.Console.Testing" Version="0.54.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UMB.CLI\UMB.CLI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="paracobNET">
      <HintPath>..\Tools\paracobNET.dll</HintPath>
    </Reference>
    <Reference Include="VGAudioCli">
      <HintPath>..\Tools\VGAudioCli.exe</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
